"""Add TutupBukuHistory model

Revision ID: 024c4a2d0203
Revises: 570157cee733
Create Date: 2026-04-04 12:04:20.093786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024c4a2d0203'
down_revision = '570157cee733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutup_buku_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_periode', sa.String(length=100), nullable=False),
    sa.Column('tanggal_tutup', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutup_buku_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tutup_buku_history', ['tutup_buku_id'], ['id'])

    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutup_buku_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tutup_buku_history', ['tutup_buku_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tutup_buku_id')

    with op.batch_alter_table('other_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tutup_buku_id')

    op.drop_table('tutup_buku_history')
    # ### end Alembic commands ###
