"""Add other_transactions table

Revision ID: 0d65dd4aa868
Revises: 429a1522a57d
Create Date: 2025-05-22 18:44:04.804059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d65dd4aa868'
down_revision = '429a1522a57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=False),
    sa.Column('pemasukan', sa.Integer(), nullable=True),
    sa.Column('pengeluaran', sa.Integer(), nullable=True),
    sa.Column('metode_pembayaran', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('other_financials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_financials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DATE(), nullable=False),
    sa.Column('keterangan', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pemasukan', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pengeluaran', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metode', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('other_transactions')
    # ### end Alembic commands ###
