"""create surat_jalan table

Revision ID: 179a49d93a44
Revises: f8a68277097a
Create Date: 2025-05-20 14:28:53.820015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179a49d93a44'
down_revision = 'f8a68277097a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_jalan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('no_kendaraan', sa.String(length=50), nullable=False),
    sa.Column('tujuan', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('supir', sa.String(length=100), nullable=True),
    sa.Column('penerima', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor')
    )
    op.create_table('surat_jalan_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surat_jalan_id', sa.Integer(), nullable=True),
    sa.Column('nama_barang', sa.String(length=100), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['surat_jalan_id'], ['surat_jalan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surat_jalan_detail')
    op.drop_table('surat_jalan')
    # ### end Alembic commands ###
