"""create other_financials table

Revision ID: 429a1522a57d
Revises: 0feae7fe96e3
Create Date: 2025-05-22 18:23:53.519963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429a1522a57d'
down_revision = '0feae7fe96e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=False),
    sa.Column('pemasukan', sa.Integer(), nullable=True),
    sa.Column('pengeluaran', sa.Integer(), nullable=True),
    sa.Column('metode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_financials')
    # ### end Alembic commands ###
