"""add client_id to waste_oil_purchases

Revision ID: 4dea68e89020
Revises: a4361bbe5636
Create Date: 2025-05-21 15:56:41.418708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dea68e89020'
down_revision = 'a4361bbe5636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.drop_column('nama_pengepul')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_pengepul', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
