"""add is_closed column

Revision ID: 570157cee733
Revises: 9f7a3c1d2b10
Create Date: 2026-04-04 11:40:58.493475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570157cee733'
down_revision = '9f7a3c1d2b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('other_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=False))

    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    with op.batch_alter_table('other_transactions', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
