"""create client table

Revision ID: a4361bbe5636
Revises: 179a49d93a44
Create Date: 2025-05-21 13:25:42.457655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4361bbe5636'
down_revision = '179a49d93a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_client', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=200), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
