"""Ubah integer ke numeric untuk transaksi dan harga modal

Revision ID: bf762bd32f09
Revises: c928bbe91fde
Create Date: 2025-05-22 20:40:14.532424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf762bd32f09'
down_revision = 'c928bbe91fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_modal_bulanan', schema=None) as batch_op:
        batch_op.alter_column('harga_modal',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('other_transactions', schema=None) as batch_op:
        batch_op.alter_column('pemasukan',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('pengeluaran',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.alter_column('total_harga',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_oil_purchases', schema=None) as batch_op:
        batch_op.alter_column('total_harga',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('other_transactions', schema=None) as batch_op:
        batch_op.alter_column('pengeluaran',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('pemasukan',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('harga_modal_bulanan', schema=None) as batch_op:
        batch_op.alter_column('harga_modal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
