"""Add harga_modal_bulanan table

Revision ID: c928bbe91fde
Revises: 0d65dd4aa868
Create Date: 2025-05-22 20:26:59.407979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c928bbe91fde'
down_revision = '0d65dd4aa868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harga_modal_bulanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulan', sa.String(length=7), nullable=False),
    sa.Column('harga_modal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harga_modal_bulanan')
    # ### end Alembic commands ###
