"""Initial migration

Revision ID: f8a68277097a
Revises: 
Create Date: 2025-05-20 11:56:29.936504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a68277097a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('waste_oil_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pengepul', sa.String(length=100), nullable=False),
    sa.Column('tanggal_pembelian', sa.Date(), nullable=False),
    sa.Column('jumlah', sa.Float(), nullable=False),
    sa.Column('harga_per_liter', sa.Integer(), nullable=False),
    sa.Column('total_harga', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_oil_purchases')
    op.drop_table('users')
    # ### end Alembic commands ###
